Administration:
- changed-files:
  - any-glob-to-any-file: admin/**

Code:
- changed-files:
  - any-glob-to-any-file: code/**

Code Maintenance:
- changed-files:
  - any-glob-to-any-file:
    - controllers/**
    - code/__DEFINES/**
    - code/__HELPERS/**

Sound:
- changed-files: 
  - any-glob-to-any-file: sound/**

Sprite:
- changed-files:
  - any-glob-to-any-file: icons/**

Mapping:
- changed-files:
  - any-glob-to-any-file: _maps/**

Documentation:
- changed-files:
  - any-glob-to-any-file:
    - .github/**
    - README.md**

Balance:
- changed-files:
  - any-glob-to-any-file:
    - code/modules/jobs/job_types/roguetown/**
    - code/modules/spells/**
    - code/modules/clothing/**
    - code/game/objects/items/rogueweapon/**

TGS:
  changed-files:
    - any-glob-to-any-file:
        - code/__DEFINES/tgs.dm
        - code/__DEFINES/tgs.config.dm
        - code/modules/discord/tgs_commands.dm
        - code/modules/tgs/**
